#---------------------------------------#
#		TimeReward		#
#	  	by uiytt		#
#	  	version: 1.0		#
#---------------------------------------#

#How much time the player must be connected in minutes to receive the money
time_for_money: 60

#How much the player receive when he was conected enough ?
money_reward: 20.0
